# Lié à la commande de give de l'item
Item:
  material: PAPER
  name: "&bdefault"

# event = BREAK, ENCHANT, FISHING, HARVEST, KILL
# type si event =
# 				FISHING: ALL, COD, SALMON, PUFFERFISH, TROPICAL_FISH, ...
#				KILL: ALL, PLAYER, COW, PIG, ZOMBIE,  ...
# 				ENCHANT: ALL, ...
# 				BREAK: ALL, STONE, GRASS, ...
#
# conditions:
#   HAND, OFF_HAND, FEET, LEGS, CHEST, HEAD
#
# Exemple:
# Quetes:
#   0:
#     name: "Tuez 10 cochons"
#     lores:
#       - "Vous devez disposer d'une éppée en netherite"
#       - "Qui doit s'appeler &aEppee"
#     event: KILL
#     type: PIG
#     customName: "&9Groin"
#     age:
#       filter: ADULTE
#     count: 10
#     dropItem: true
#     conditions:
#       HAND:
#         material: NETHERITE_SWORD
#         name: "&aEppee"
#
#   1:
#     name: "&7Tuez 10 &2Morts vivant bébé"
#     event: KILL
#     type: ZOMBIE
#     customName: "&2Morts vivant bébé"
#     age:
#       filter: BABY
#     count: 10
#     dropItem: true
#
#   3:
#     name: "&7Cassez 10 pierres lisse"
#     event: BREAK
#     type: STONE
#     count: 10
#     dropItem: true
#     reward: # Optionnel
#       name: "&6Stone"
#       material: "STONE"
#       count: 1
#
#   4:
#     name: "&7Enchantez 10 livres"
#     event: ENCHANT
#     type: ALL
#     customName: "&2Morts vivant bébé"
#     count: 10
#     dropItem: true
#     rewards: # Optionnel
#       - "STONE:1:&bTest"
#
#   5:
#     name: "&7Pêchez 10 morues"
#     event: FISHING
#     type: COD
#     count: 10
#     dropItem: true
#
#   6:
#     name: "&7Récoltez 10 blées"
#     event: BREAK
#     type: WHEAT
#     count: 10
#     dropItem: true




Quetes:
  0:
    name: "Cassez 1 pierres"
    event: BREAK
    type: STONE
    count: 1
    dropItem: false
    conditions:
      HAND:
        material: DIAMOND_PICKAXE
        name: "&bPioche"
    reward: # Optionnel
      name: "&6Stone"
      material: "STONE"
      count: 1
  1:
    name: "Enchantez 1 livres"
    event: ENCHANT
    type: ALL
    count: 1
    dropItem: false
    rewards: # Optionnel
      - "STONE:1:&bTest"
  2:
    name: "Pêchez 1 morues"
    event: FISHING
    type: COD
    count: 1
    dropItem: false
  3:
    name: "Récoltez 1 blées"
    event: BREAK
    type: WHEAT
    count: 1
    dropItem: false
  4:
    name: "Tuez 1 cochons"
    event: KILL
    type: PIG
    customName: "Groin" # Optionnel
    age: # Optionnel
      filter: ADULTE
    count: 1
    dropItem: false
    conditions:
      HAND:
        material: NETHERITE_SWORD
        name: "&aEppee"


Rewards:
  Inventory:
    0:
      name: "&bPierre lisse"
      material: STONE
      count: 1
    1:
      name: "&bTerre magique"
      material: GRASS_BLOCK
      count: 1
      pourcent: 95